Resources:
  LeadsTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: LeadsTable
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: id
          AttributeType: S
      KeySchema:
        - AttributeName: id
          KeyType: HASH
